apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "Q2VzQk55VllSQkFSemRMbEF6bG83enVrTEhiemNnQlIwNWRPYlRLSW5Na2lZcFo1N0FTUUpRUUo5OUJEQUNmaE1rNVhKM3czQUFBQUFDT0dwaHY2"

---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  ORDER_QUEUE_USERNAME: "c2VuZGVy"
  ORDER_QUEUE_PASSWORD: "bVUxMzFkV3pKdG9ydFQwZzMvRjQwTUREZ2hPcExZaEZrK0FTYkoveU9LND0="

---
apiVersion: v1
kind: Secret
metadata:
  name: makeline-service-secret
type: Opaque
data:
  ORDER_QUEUE_LISTENER_USERNAME: "bGlzdGVuZXI="
  ORDER_QUEUE_LISTENER_PASSWORD: "M3p0bk51NkRmeHh2cHBac053c1hsZzFCLzFtS2dxSENqK0FTYktHMmkwQT0="
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

